class Translates {
  dynamic translate = {
    "vn": {
      "base": "Cơ sở",
      "employee": "Nhân viên",
      "product": "Sản phẩm",
      "category": "danh mục",
      "want_install_folder": "Bạn chưa có thư mục chứa dữ liệu, bạn có muốn tạo nó không",
      "create_folder_data": "Tạo thư mục dữ liệu",
      "status_base_shared": "Trạng thái: chia sẽ bởi",
      "status_base_owner": "Trạng thái: Chủ sở hữu ",
      "title_base_infomation": "Thông tin cơ sở",
      "title_return_main_base": "Trở về cơ sở chính",
      "title_your_infomation": "Thông tin cá nhân",
      "logout": "Đăng xuất",
      "system_pos": "Hệ thống bán hàng",
      "manage_base": "Quản lý cơ sở",
      "account": "Tài khoản",
      "global_setting": "Cấu hình chung",
      "in": "Nhập",
      "out": "Xuất",
      "product_name": "Hàng",
      "select_reason": "Chọn lý do",
      "price": "Giá",
      "quantity": "SL",
      "quantity_full": "Số lượng",
      "money": "Tiền",
      "guest": "Khách lẻ",
      "total_money_short": "TS",
      "product_not_found": "Không tìm thấy sản phẩm",
      "order": "Đơn hàng",
      "customer": "Khách hàng",
      "pos": "Bán hàng",
      "video": "video",
      "chat": "chat",
      "title_product_properties": "Thuộc tính sản phẩm",
      "title_product_dependent": "sản phẩm phụ thuộc",
      "title_product_from_warehouse": "Sản phẩm theo kho",
      "title_categories": "Các danh mục",
      "title_value_properties": "Giá trị thuộc tính",
      "title_attributeset": "Bộ thuộc tính",
      "title_attributeset_use": "Bộ thuộc tính sử dụng",
      "discount": "chiết khấu",
      "discount_category": "Mục chiết khấu",
      "move_product_in_local": "Chuyển hàng nội bộ",
      "stock_diary": "Nhật ký kho",
      "label_product": "Nhãn sản phẩm",
      "warehouse": "Kho bãi",
      "inventory_report": "Báo cáo kiểm kê",
      "stock_is_running_out": "Hàng sắp hết",
      "show_detailed_inventory": "Hiện kiểm kê chi tiết",
      "check_diary": "Kê nhật ký",
      "tax_report": "Báo cáo thuế",
      "warehouse_manage": "Quản lý kho",
      "report": "Báo cáo",
      "are_you_want_delete_this_property": "Bạn có muốn xóa thuộc tính này không ?",
      "filter_product": "Lọc sản phẩm",
      "barcode": "Mã vạch",
      "title_product_name": "Tên sản phẩm",
      "price_buy": "Giá mua",
      "price_sell": "Giá bán",
      "show_result": "Hiện kết quả",
      "price_and_tax": "Giá + Thuế",
      "total_amount_incurred": "Tổng số tiền phát sinh",
      "total_money": "Tổng tiền",
      "ok": "Đồng ý",
      "cancel": "Hủy bỏ",
      "select_category": "Chọn danh mục",
      "add_warehouse": "Thêm kho chứa",
      "name": "Tên",
      "address": "Địa chỉ",
      "stock_current": "Số lượng hiện có",
      "warehouse_code": "Mã kho",
      "day": "Ngày",
      "reason": "Lý do",
      "warehouse_infomation": "Thông tin kho chứa",
      "debt": "Nợ",
      "notes": "Ghi chú",
      "max_debt": "Nợ tối đa",
      "current_debt": "Nợ hiện tại",
      "debt_expire_time": "TT cuối",
      "give": "Đưa",
      "money_back": "Thối",
      "total": "Tổng số",
      "money_left": "Tiền còn",
      "payment": "Thanh toán",
      "cash": "Tiền mặt",
      "payable": "công nợ",
      "active": "Hoạt động",
      "inactive": "Không hoạt động",
      "select_currency": "Chọn loại tiền tệ",
      "select_payment_method": "Chọn hình thức thanh toán",
      "find_customer": "Tìm khách hàng",
      "owner": "Chủ sở hữu",
      "manage": "Quản trị",
      "main_screen": "Màn hình chính",
      "wifi_printer": "Máy in wifi",
      "bluetooth_printer": "Máy in bluetooth",
      "add_printer": "Thêm máy in",
      "type_printer": "Loại máy in",
      "select_type_printer": "Chọn loại máy in",
      "ip_address": "Địa chỉ ip",
      "device_name": "Tên thiết bị",
      "bluetooth_select": "Chọn thiết bị bluetooth",
      "printer_infomation": "Thông tin máy in",
      "receipt": "Hóa đơn",
      "price_after_discount": "Giá sau chiết khấu",
      "type_discount": "Loại chiết khấu",
      "select_type_discount": "Chọn loại chiết khấu",
      "parent_category": "Danh mục cha",
      "select_parent_category": "Chọn danh mục cha",
      "attribute": "Thuộc tính",
      "select_attribute": "Chọn thuộc tính",
      "storage_charges": "Phí lưu kho",
      "volume_in_warehouse": "Thể tích trong kho",
      "product_queue": "Thứ tự sản phẩm",
      "show_in_the_list": "Hiển thị trong danh mục",
      "dependent": "Phụ thuộc",
      "need_to_weigh": "Cần cân đo",
      "attribute_name": "Tên thuộc tính",
      "attribute_value": "Giá trị thuộc tính",
      "type_data": "Kiểu dữ liệu",
      "string": "Chữ",
      "number": "Số",
      "add": "Thêm",
      "add_product": "Thêm sản phẩm",
      "auto_calculate": "Tính giá tự động",
      "parent_tax": "Chiếc khấu cấp trên",
      "update_product": "Cập nhật sản phẩm",
      "transaction": "Giao dịch",
      "contact": "Liên hệ",
      "language": "Ngôn ngữ",
      "printer": "Máy in"
    },
    "en": {
      "base": "Base",
      "employee": "Employee",
      "product": "Product",
      "category": "Category",
      "want_install_folder": "Bạn chưa có thư mục chứa dữ liệu, bạn có muốn tạo nó không",
      "create_folder_data": "Tạo thư mục dữ liệu",
      "status_base_shared": "Status: Shared by",
      "status_base_owner": "Status: Owner",
      "title_base_infomation": "Base infomation",
      "title_return_main_base": "Back main base",
      "title_your_infomation": "Your infomation",
      "logout": "Logout",
      "system_pos": "Pos system",
      "manage_base": "Base manage",
      "account": "Account",
      "global_setting": "Global setting",
      "in": "In",
      "out": "Out",
      "product_name": "Name",
      "select_reason": "Select reason",
      "price": "Price",
      "quantity": "Qty",
      "quantity_full": "Quantity",
      "money": "Money",
      "guest": "Guest",
      "total_money_short": "TM",
      "product_not_found": "product not found",
      "order": "Order",
      "customer": "Customer",
      "pos": "Pos-system",
      "video": "video",
      "chat": "chat",
      "title_product_properties": "Product properties",
      "title_product_dependent": "Product dependent",
      "title_product_from_warehouse": "Product from warehouse",
      "title_categories": "Categories",
      "title_value_properties": "Value properties",
      "title_attributeset": "Attributeset",
      "title_attributeset_use": "Attributeset use",
      "discount": "Discount",
      "discount_category": "Discount_category",
      "move_product_in_local": "Move product in local",
      "stock_diary": "Stock diary",
      "label_product": "Label product",
      "warehouse": "Warehouse",
      "inventory_report": "Inventory report",
      "stock_is_running_out": "Stock is running out",
      "show_detailed_inventory": "Show detailed inventory",
      "check_diary": "Check diary",
      "tax_report": "Tax report",
      "warehouse_manage": "Warehouse manage",
      "report": "Report",
      "are_you_want_delete_this_property": "Do you want to delete this attribute?",
      "filter_product": "Filter products",
      "barcode": "Barcode",
      "title_product_name": "Product name",
      "price_buy": "Price buy",
      "price_sell": "Price sell",
      "show_result": "Show result",
      "price_and_tax": "Price + Tax",
      "total_amount_incurred": "Total amount incurred",
      "total_money": "Total money",
      "ok": "OK",
      "cancel": "Cancel",
      "select_category": "select_category",
      "add_warehouse": "Add warehouse",
      "name": "Name",
      "address": "Address",
      "stock_current": "stock_current",
      "warehouse_code": "Warehouse code",
      "day": "Day",
      "reason": "Reason",
      "warehouse_infomation": "warehouse infomation",
      "debt": "Debt",
      "notes": "notes",
      "max_debt": "Max debt",
      "current_debt": "Current debt",
      "debt_expire_time": "Expire",
      "give": "Give",
      "money_back": "Back",
      "total": "Total",
      "money_left": "Money left",
      "payment": "Payment",
      "cash": "Payment",
      "payable": "Payable",
      "active": "Active",
      "inactive": "Inactive",
      "select_currency": "Select currency",
      "select_payment_method": "Select payment method",
      "find_customer": "Find customer",
      "owner": "Owner",
      "manage": "Manage",
      "main_screen": "Main screen",
      "wifi_printer": "Wifi printer",
      "bluetooth_printer": "Bluetooth printer",
      "add_printer": "Add printer",
      "type_printer": "Type printer",
      "select_type_printer": "Select type printer",
      "ip_address": "Ip address",
      "device_name": "Name device",
      "bluetooth_select": "select bluetooth",
      "printer_infomation": "Printer infomation",
      "receipt": "Receipt",
      "price_after_discount": "Price_after_discount",
      "type_discount": "Type discount",
      "select_type_discount": "Select type discount",
      "parent_category": "Parent category",
      "select_parent_category": "select_parent_category",
      "attribute": "Attribute",
      "select_attribute": "Select_attribute",
      "storage_charges": "Storage charges",
      "volume_in_warehouse": "Volume in warehouse",
      "product_queue": "Product queue",
      "show_in_the_list": "Show in the list",
      "dependent": "Dependent",
      "need_to_weigh": "Need to weigh",
      "attribute_name": "Attribute name",
      "attribute_value": "Attribute value",
      "type_data": "Type data",
      "string": "String",
      "number": "Number",
      "add": "Add",
      "add_product": "Add product",
      "auto_calculate": "Auto calculate",
      "update_product": "Update product",
      "transaction": "Transaction",
      "contact": "Contact",
      "language": "Language",
      "printer": "Printer"
    }
  };

  //stateBase.translate[stateBase.languageSelected]["total_money_short"]
  //state.translate[state.languageSelected]["total_money_short"]
  //final stateBase = ref.watch(baseProvider);

  // var base = {"vn": "Cơ sở", "en": "Base"};
  // var employee = {"vn": "Nhân viên", "en": "Employee"};
  // var product = {"vn": "Sản phẩm", "en": "Product"};
  // var category = {"vn": "Danh mục", "en": "Category"};
  // var wantInstallFolder = {"vn": "Bạn chưa có thư mục chứa dữ liệu, bạn có muốn tạo nó không", "en": ""};
  // var createFolderData = {"vn": "Tạo thư mục dữ liệu", "en": "ghjghjgh"};
  // var statusBaseShared = {"vn": "Trạng thái: chia sẽ bởi", "en": "asdasdasd"};
  // var statusBaseOwner = {"vn": "Trạng thái: Chủ sở hữu", "en": "dsdsdsd"};
  // var titleBaseInfomation = {"vn": "Thông tin cơ sở", "en": "sdsgfdg"};
  // var titleReturnMainBase = {"vn": "Trở về cơ sở chính", "en": "dfgdfgdfg"};
  // var titleYourInfomation = {"vn": "Thông tin cá nhân", "en": "asdasd"};
  // var logout = {"vn": "Đăng xuất", "en": ""};
  // String getTranslate(String key, [String languageSelected = "vn"]) {
  //   String dataTranslate = "";
  //   if (key == "base") {
  //     dataTranslate = base[languageSelected]!;
  //   } else if (key == "employee") {
  //     dataTranslate = employee[languageSelected]!;
  //   } else if (key == "wantInstallFolder") {
  //     dataTranslate = wantInstallFolder[languageSelected]!;
  //   } else if (key == "createFolderData") {
  //     dataTranslate = createFolderData[languageSelected]!;
  //   } else if (key == "statusBaseShared") {
  //     dataTranslate = statusBaseShared[languageSelected]!;
  //   } else if (key == "statusBaseOwner") {
  //     dataTranslate = statusBaseOwner[languageSelected]!;
  //   } else if (key == "titleBaseInfomation") {
  //     dataTranslate = titleBaseInfomation[languageSelected]!;
  //   } else if (key == "titleReturnMainBase") {
  //     dataTranslate = titleReturnMainBase[languageSelected]!;
  //   } else if (key == "titleYourInfomation") {
  //     dataTranslate = titleYourInfomation[languageSelected]!;
  //   } else if (key == "logout") {
  //     dataTranslate = logout[languageSelected]!;
  //   }
  //   return dataTranslate;
  // }
}
